name: setup-node
description: Setup Node.js and install npm packages

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version-file: package.json
        cache-dependency-path: package-lock.json
        package-manager-cache: true
    - run: npm install
      shell: bash
