name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: tibdex/github-app-token@c2055a00597a80f713b78b1650e8d3418f4d9a65
        id: generate_token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: Retrieve version
        id: retrive-version
        run: |
          VERSION=$(node -p -e 'require("./package.json").version')
          echo "version=v${VERSION}" >> "$GITHUB_OUTPUT"
      - name: Check release
        id: check-release
        run: |
          gh release view ${{ steps.retrive-version.outputs.version }} &> /tmp/gh_release_view.log && echo "release exists" || echo "not found or error"
          cat /tmp/gh_release_view.log
          RELEASE_EXIST=$(cat /tmp/gh_release_view.log | grep -q "release not found" && echo "false" || echo "true")
          echo "exist=$RELEASE_EXIST" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      - name: Create tag
        if: steps.check-release.outputs.exist == 'false'
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          TAG=${{ steps.retrive-version.outputs.version }}
          git tag $TAG
          git push origin $TAG
      - name: Create release
        if: steps.check-release.outputs.exist == 'false'
        run: |
          gh release create ${{ steps.retrive-version.outputs.version }} --generate-notes --draft
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
