name: Release version check

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  release_version_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Write current release versions
        run: |
          curl -s https://api.github.com/repos/suzuki-shunsuke/tfcmt/releases | jq "[.[].tag_name]" > ./src/versions.json
      # TODO(shirakiya): A pull-request should be created if diffs are exist in `versions.json`.
      - name: Check diff
        run: git --no-pager diff  --exit-code --ignore-space-at-eol ./src/versions.json
