name: Release version check

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  release_version_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: generate_token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: Write current release versions
        run: |
          curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/suzuki-shunsuke/tfcmt/releases?per_page=100" \
          | jq "[.[].tag_name]" > ./src/versions.json
      - name: Check diff
        id: check_diff
        run: |
          if [ "$(git --no-pager diff --ignore-space-at-eol ./src/versions.json | wc -l)" -gt "0" ]; then
            echo "Detected diff.  See status below:"
            git --no-pager diff --ignore-space-at-eol ./src/versions.json
            echo "is_exist=true" >> $GITHUB_OUTPUT
          else
            echo "is_exist=false" >> $GITHUB_OUTPUT
          fi
      - name: Extract latest version
        id: extract_latest_version
        run: |
          LATEST_VERSION=$(cat ./src/versions.json | jq -r ".[0]")
          echo "version=${LATEST_VERSION}" >> "$GITHUB_OUTPUT"
      - name: Push if new release versions are found
        id: push
        if: steps.check_diff.outputs.is_exist == 'true'
        run: |
          BRANCH="new_version_released_${{ github.run_id }}"
          git switch -c $BRANCH

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add ./src/versions.json
          COMMIT_MESSAGE="update latest tfcmt version to ${{ steps.extract_latest_version.outputs.version }}"
          git commit -m "$COMMIT_MESSAGE"
          git push origin $BRANCH

          echo "branch=${BRANCH}" >> "$GITHUB_OUTPUT"
          echo "commit_message=${COMMIT_MESSAGE}" >> "$GITHUB_OUTPUT"
      - name: Create pull-request if new release versions are found
        if: steps.check_diff.outputs.is_exist == 'true'
        run: |
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          gh pr create -B main -H ${{ steps.push.outputs.branch }} -t "${{ steps.push.outputs.commit_message }}" -b "This pull-request is created by GitHub Actions. Run $RUN_URL"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
