name: Update major tag

on:
  release:
    types:
      - released

permissions:
  contents: write

jobs:
  update_major_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Update major tag
        run: |
          TAG=${GITHUB_REF#refs/tags/} # v1.2.3
          MAJOR="${TAG%%.*}"           # v1
          MESSAGE="Release ${TAG}"
          git tag -fa "${MAJOR}" -m "${MESSAGE}"
          git push --force origin "${MAJOR}"
