name: Update major tag

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: write

jobs:
  update_major_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Update tag
        run: |
          TAG=${GITHUB_REF#refs/tags/} # v1.2.3
          MAJOR="${TAG%%.*}"           # v1

          MESSAGE="Release ${TAG}"

          git tag -fa "${MAJOR}" -m "${MESSAGE}"
          git push --force origin "${MAJOR}"
